[package]
name = "todo"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4"
directories = "5.0.1"
include_dir = "0.7.4"
once_cell = "1.10"
pulldown-cmark = "0.12.1"
self-replace = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
